### PR TITLE
Update framework

### PR DESCRIPTION
**Pull request by matthewtrask**

### CODE REVIEW

**Comment by matthewtrask** [comment]
Certainly not finished, but a start to get things going. Brought in a few packages, set up src/, tests/, config/ and some others and will start to move things. figured I would start with a global config option first. I know you wanted routing as a big option, so I brought in the league package for it.

**Comment by michael-delle** [comment]
It is a start 👍 

I have a bunch of information that needs to be added to the Wiki still and one of those things is how the framework finds custom files that are used instead of the frameworks.

You can create an application/ folder, in the root folder, which has the same structure as framework/application/.
In the Utility class (framework/application/modules/Utility/Utility.php) there is a method called locateFile() which first looks for the file in framework/application/ and if it's not there it checks application/ for that file instead.

The framework isn't MVC, yet, but the controllers need to go into framework/application/controllers/<ControllerName>/ and classes go into framework/application/modules/<ModuleName>/

I'll accept the merge and make the changes myself to show you. And composer.lock shouldn't be committed to the repo so I will delete that and add it to the .gitignore

**Comment by matthewtrask** [comment]
I would actually advocate for keeping the .lock file, otherwise dependencies can get out of sync if people are not regularly running `composer update`.

As for the folder structure, I was aiming to get it to a more manageable structure which is why I went with what I did, but I will take a look at things that you have mentioned tonight.

**Comment by michael-delle** [comment]
Yeah, I get it. We'd like to keep it nice and clean, and move things around later.

We appreciate that you got the ball rolling :)

**Pull request merged**
